### ISSUE TITLE
Auth mime type issue?

### ISSUE THREAD

**Issue by deadlyfingers** [CatalystCode/ibex-dashboard#109]
Is there a bug loading dashboards after auth? 
Chrome error:
```
Refused to execute script from 'http://localhost:3000/api/dashboards' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```
Firefox error:
```
https://login.microsoftonline.com/common/oauth2/authorize?redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fauth%2Fopenid%2Freturn&response_type=code%20id_token&response_mode=query&client_id=X&state=X&nonce=X&scope=openid&x-client-SKU=passport-azure-ad&x-client-Ver=3.0.5” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).
```

**Comment by obsoleted** [comment]
I'm hitting the same issue. I think it is some sort of misconfiguration since the error is a result of the`api/dashboards` call initiating the auth redirect flow. The consent flow page is then being treated as the response from `api/dashboards` which is indeed not a script. 

This is surprising because I would have thought the initial page load would kick off the auth/consent flow.

Any tips on setting up the auth configuration @morsh ?

**Comment by morsh** [comment]
@obsoleted Did you activate authentication?
This feature still needs fine tuning, so for now I would turn it off via `http://localhost:3000/setup` or by opening:
`/repo_location/server/config/setup.private.json` and set `enableAuthentication` to false.

I will update once this feature is more stable / tested.

**Comment by obsoleted** [comment]
Ok good to know. I did turn auth on. For the purposes of our hack we can skip auth. But since were were getting to adding more data source connection configuration (i.e. more secrets in the config) I wanted to try out the auth flow to see what was or wasn't gated by auth.

My setup was as follows:

```json
{"admins":["xxxxxx@microsoft.com"],"stage":"configured","enableAuthentication":true,"allowHttp":true,"redirectUrl":"http://localhost:3000/auth/openid/return","clientID":"ee8a1746-25f1-4225-adea-cf59d67e5b30","clientSecret":"xxxxxxx"}
```

**Comment by morsh** [comment]
@obsoleted I think the problem is with the port - try setting port to 4000 (not 3000)

**Comment by obsoleted** [comment]
@morsh Oh! Didn't even realize it was also listening on 4000. Since the browser window that opens up is on 3000. A quick test does show that at least going to http://localhost:4000/ gets me to the azure ad login page. So seems much better :) 

Thanks!

**Comment by morsh** [comment]
@obsoleted - cool, happy this moved forward :)

**Comment by obsoleted** [comment]
So I guess my confusion was that since the dev server (that listens to 3000) is only used for serving up the react app it doesn't use our node server implementation (that the api endpoint is served on). As a result the react app bypasses the auth middleware (because that isn't used). So the first call to the api endpoint naturally tried to get auth and failed (with the error mentioned in the first post).

To run locally with auth I had to `yarn build` and `yarn start` and then only use `http://localhost:4000/`. This of course doesn't have the nice dev server features like reloading when the react app changes.

**Comment by morsh** [comment]
@obsoleted you should still be able to run `yarn run dev:start` and use port 3000. The dev environment knows how to proxy requests to port 4000.

**Comment by obsoleted** [comment]
Yup the api request are proxied. But only the proxied ones require or ask for auth. Which i think is the problem I hit.

**Comment by morsh** [comment]
Yeah, the flow in development is not the same as in production. This is a necessity because of the method we've chosen
