### ISSUE TITLE
[Create dashboard] Cancel should delete the new dashboard

### ISSUE THREAD

**Issue by Ilanak** [CatalystCode/ibex-dashboard#280]
![image](https://user-images.githubusercontent.com/13463870/29122014-7e32645c-7d19-11e7-8849-04fa25f6a57d.png)

**Comment by eladiw** [comment]
Since this is actually after the actual dashboard creation. both actually and logically. making a 'revert' , delete is a bit dirty.
i think that an elegant yet simple solution would be to rename from 'cancel' to 'skip' , because thats what this actually is...a dashboard with no connection (because the step was skipped).
Thoughts?

**Comment by morsh** [comment]
Add two buttons instead of 'Cancel' - 'Skip' & 'Delete'

**Comment by deadlyfingers** [comment]
Don't see the benefit of a skip button, as all you will end up with is a blank dashboard / with toast errors popping up. 
Less options would be better, in fact only 2 options are required - save / delete.
