### ISSUE TITLE
Add help section on Templates

### ISSUE THREAD

**Issue by morsh** [CatalystCode/ibex-dashboard#72]
@deadlyfingers - please review this ask, not sure if this flow would work well.

Instead of the About/Help section in the global application, add a help section on dashboard templates that will be accessible via the dashboard creation screen & the dashboard itself after it was created.

This can be done by leveraging the InfoDrawer component.

This data might alternatively be displayed when clicking "Create" to create the dashboard.

**Comment by deadlyfingers** [comment]
I think I would prefer only to use lhs sidebar for dashboards (most frequently used items). 
Add dashboard, or change settings will happen less often so maybe these can be placed under a header account menu / rhs side panel

https://react-md.mlaursen.com/components/toolbars

**Comment by deadlyfingers** [comment]
Using dialog box for rendering html. One issue is closing dialog box on dashboard page:
`You specified that the `FocusContainer` should focus an element on mount, but a focusable element was not found in the children. This could be because the `initialFocus` prop is an invalid id or query selector, or the children do not contain a valid focusable element.undefined`
